'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from 'next/navigation';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Issue Management",
//   description: "Generated by chung-ang university students",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname();
  const hideHeaderElements = pathname === "/create_account" || pathname === "/";  


  const handleLogout = () => {
    router.push('/'); // Redirects to the home page
  };

  return (
    <html lang="en">
      <body>
        <header>
          <h1>Issue Management</h1>
          <div className="header-right">
          {!hideHeaderElements && (
          <>
            <span>Tester</span>
            <button onClick={handleLogout}>Log out</button>
          </>
          )}
        </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
