import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Issue Management",
  description: "Generated by chung-ang university studentss",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Issue Management</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
